name: Build Artifacts

on:
   workflow_dispatch:
      inputs:
         refToBuild:
            description: 'Branch, tag, or commit SHA1 to build'
            required: true
            type: string
            default: 'HEAD'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.refToBuild }}
          fetch-depth: 0
      
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
        
      - name: Build with Ant
        run: ant -f build-auto.xml dist
        
      - name: Move builds to appropriate artifact folders
        run: |
          # Remove all unnecessary build folders since we will only release builds archived with 7-Zip
          cd dist
          rm -R -- */
          cd ..
          # Make directories for artifact releases and move each build to their respective folders
          mkdir -p dist/{buildWindows/x86,buildWindows/amd64,buildLinux/x86,buildLinux/amd64,buildmacOS}
          mv dist/*linux-amd64* dist/buildLinux/amd64/
          mv dist/*linux-x86* dist/buildLinux/x86/
          mv dist/*windows-x86* dist/buildWindows/x86/
          mv dist/*windows-amd64* dist/buildWindows/amd64/
          mv dist/*macosx* dist/buildmacOS/
     
      - name: Publishing Windows 32-bit build
        uses: actions/upload-artifact@v4
        with:
          name: Windows 32-bit build
          path: dist/buildWindows/x86

      - name: Publishing Windows 64-bit build
        uses: actions/upload-artifact@v4
        with:
          name: Windows 64-bit build
          path: dist/buildWindows/amd64
      
      - name: Publishing Linux 32-bit build
        uses: actions/upload-artifact@v4
        with:
          name: Linux 32-bit build
          path: dist/buildLinux/x86

      - name: Publishing Linux 64-bit build
        uses: actions/upload-artifact@v4
        with:
          name: Linux 64-bit build
          path: dist/buildLinux/amd64

      - name: Publishing macOS build
        uses: actions/upload-artifact@v4
        with:
          name: macOS build
          path: dist/buildmacOS
          
